# Problem 1 

In [4]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
x = np.array([5, 3, 1, 4, 2])
print(x)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x_siralama= np.sort(x)
print(x_siralama)


[5 3 1 4 2]
[1 2 3 4 5]


# Problem 2

In [20]:
import numpy as np
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
array = np.array([10, 15, 30, 45, 60])
print(array)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
array2 = np.arange(5, 16)

print(array2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
array3 = np.arange(50, 101, 5)

print(array3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
array4 = np.zeros(10)

print(array4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
array5 = np.ones(10)

print(array5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
numbers = np.linspace(0, 100, 5)

print(numbers)


# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
numbers2 = np.linspace(10, 30, 5)

print(numbers2)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
numbers3 = np.linspace(-1, 1, 10)

print(numbers3)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
matrix2 = np.random.randint(10, 51, size=(3, 5))

print(matrix2)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
row_sums = np.sum(matrix2, axis=1)

column_sums = np.sum(matrix2, axis=0)

print("Satır Toplamları:")
print(row_sums)

print("Sütun Toplamları:")
print(column_sums)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
maximum_value = np.max(matrix2)
minimum_value = np.min(matrix2)
average_value = np.mean(matrix2)

print("En Büyük Değer:", maximum_value)
print("En Küçük Değer:", minimum_value)
print("Ortalama Değer:", average_value)


# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.argmax(matrix2)

print("En Büyük Değerin İndeksi:", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
array = np.arange(10, 21)

ilk_uc = array[:3]
print(ilk_uc)

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(array[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(array[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
matrix = np.array([[30, 23, 41, 15, 34],
                   [11, 39, 42, 48, 32],
                   [13, 44, 28, 12, 19]])

print("Matris:")
print(matrix)

element = matrix[1, 2]

print("2. Satır 3. Sütundaki Eleman:")
print(element)

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(matrix[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.square(matrix))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matrix4 = np.random.randint(-50, 51, size=(3, 5))

print("Matris:")
print(matrix4)


positive_even_numbers = matrix[(matrix4 > 0) & (matrix4 % 2 == 0)]

print("Pozitif Çift Sayılar:")
print(positive_even_numbers)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[10. 15. 20. 25. 30.]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[[31 46 37 42 37]
 [46 30 34 38 32]
 [13 18 18 46 44]]
Satır Toplamları:
[193 180 139]
Sütun Toplamları:
[ 90  94  89 126 113]
En Büyük Değer: 46
En Küçük Değer: 13
Ortalama Değer: 34.13333333333333
En Büyük Değerin İndeksi: 1
[10 11 12]
[20 19 18 17 16 15 14 13 12 11 10]
10
Matris:
[[30 23 41 15 34]
 [11 39 42 48 32]
 [13 44 28 12 19]]
2. Satır 3. Sütundaki Eleman:
42
[30 11 13]
[[ 900  529 1681  225 1156]
 [ 121 1521 1764 2304 1024]
 [ 169 1936  784  144  361]]
Matris:
[[ 25  45  49 -22   7]
 [ -6 -10  -6 -27 -12]
 [  3 -10 -45  29   1]]
Pozitif Çift Sayılar:
[]
