# Problem 1

In [7]:
# 1 - numpy kütüphanesini import edin
import numpy as np 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
matris = np.random.randint(0, 11, size=(1, 5))
print(matris)

# 3 - matris'in boyutunu öğrenin
print(matris.shape)
# 4 - matris'i yeniden boyutlandırın
matris= matris.reshape(5,1)
print(matris)
# 5 - matris'in boyut sayısını öğrenin
print(matris.ndim)


[[7 8 4 9 3]]
(1, 5)
[[7]
 [8]
 [4]
 [9]
 [3]]
2


# Problem 2

In [20]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
matris = np.arange(1, 11, 2).reshape(5, 1)
print(matris)
print("------------------------")
# 2 - Oluşturduğunuz matrisi parçalayın
matris_parcala= np.split(matris, 5)
for parca in matris_parcala:
    print(parca)
print("-----------------------------------")
# 3 - Parçalanmış matrisleri birleştirin
print(np.concatenate([matris_parcala]))

[[1]
 [3]
 [5]
 [7]
 [9]]
------------------------
[[1]]
[[3]]
[[5]]
[[7]]
[[9]]
-----------------------------------
[[[1]]

 [[3]]

 [[5]]

 [[7]]

 [[9]]]


# Problem 3

In [32]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
numbers = np.arange(5, 101, 2)
np.random.shuffle(numbers)
matrix = numbers[:10].reshape((5, 2))
print(matrix)
# 2 - matris'in özelliklerini inceleyin


[[37  7]
 [87 53]
 [79 63]
 [61 39]
 [29 65]]
