# Numpy

* Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
* Veri analizlerinde kullanılır.
* Bilgisayar kurmak için pip insall numpy komutu ile kurulabilir.
* Birimsel hesaplamalar için kullanılır.
* Arraylar/ çok boyutku arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir.
* Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

# Neden Numpy?

In [135]:
# Klasik yöntem

a = [1,2,3,4,]
b = [2,3,4,5]
ab= []
for i in range(0,len(a)):
    ab.append(a[i]*b[i])
print(ab)

[2, 6, 12, 20]


In [136]:
pip install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [137]:
# Numpy ile
import numpy as np

a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


## .reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriniz

In [138]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi= x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## .shape() ile arraylerin boyutlarını öğrenebiliriz.

In [139]:
print(multi.shape)

(3, 3)


## .ndim ile arraylerin boyut sayısını öğrenebiliriz.

In [140]:
print(x.ndim)

1


In [141]:
print(multi.ndim)

2


# Birleştirme (Concatenation)
* .concatenate() fonksiyonu ile birleştirme yapabiliriz.

In [142]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [143]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


axis = 0 ise satır bazında birleştirme yapar
axis = 1 ise sütun bazında birleştirme yapar

In [144]:
print(np.concatenate([a,a],axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


# Array Ayırma (Splitting)

* .split() fonksiyonu ile array ayırma yapabiliriz.

In [145]:
m=np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


* vsplit() fonksiyonu ile array yatay olarak ayırma yapabiliriz.

In [146]:
n=np.arange(16).reshape(4,4)
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

* hsplit() fonksiyonu ile array dikey olarak ayırma yapabiliriz.

In [147]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

### np.arrange()
* Belli bir aralıkta sayıları oluşturmak için kullanılır.
* np.arange(start,stop,step)

In [148]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

### np.zeros

* 0'lardan oluşan numpy dizisi oluşturması için kullanılır.

In [149]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

### np.ones

* 1'lerden oluşan numpy dizisi oluşturması için kullanılır.

In [150]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### np.linspace()

* Belli bir aralıkta sayıları oluşturmak için kullanılır.
* np.linpace(başlangıç,bitiş,bölünecek aralık)

In [151]:
np.linspace(5,25,7)

array([ 5.        ,  8.33333333, 11.66666667, 15.        , 18.33333333,
       21.66666667, 25.        ])

In [152]:
np.random.randint(0,100,5)

array([77, 71, 54, 38, 49])

In [153]:
np.random.randint(2,22,2)

array([13, 17])

# Numpy Array'in Özellikleri

* ndim: Boyut sayısı
* shape: Boyut bilgisi
* size: Toplam eleman sayısı
* dtype: Veri tipi

In [154]:
a = np.random.randint(10,size=10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


# Array Sıralama(Sorting)

* Array sıralama işlemleri yapmak için nupy kütüphanesinde yer alan sort() fonksiyonu kullanılır.


In [155]:
v=np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [156]:
m=np.random.normal(20,5,(3,3))
print(m)
print("---------------------------------------")
print(np.sort(m,axis=0))
print("---------------------------------------")
print(np.sort(m,axis=1))

[[34.87027174 21.65730236 19.21561295]
 [26.86597831 14.30928525 19.40645141]
 [17.27264195 16.61444078 20.49020336]]
---------------------------------------
[[17.27264195 14.30928525 19.21561295]
 [26.86597831 16.61444078 19.40645141]
 [34.87027174 21.65730236 20.49020336]]
---------------------------------------
[[19.21561295 21.65730236 34.87027174]
 [14.30928525 19.40645141 26.86597831]
 [16.61444078 17.27264195 20.49020336]]


# Index ile elemanlara erişmek

* Aynı listelerde olduğu gibi index ile elemanlara erişebiliriz.

In [157]:
a = np.random.randint(10, size=10)
print(a[0])

5


In [158]:
print(a[-1])

5


In [159]:
a[0]=100
print(a)

[100   4   6   2   7   7   0   1   8   5]


In [160]:
x = np.random.randint(10,size=(3,5))
print(x)



[[0 3 7 5 7]
 [7 6 2 9 7]
 [4 0 2 9 6]]


In [161]:
print(x[0,0])

0


In [162]:
print(x[1,1])

6


In [163]:
x[1,4]=100
print(x)

[[  0   3   7   5   7]
 [  7   6   2   9 100]
 [  4   0   2   9   6]]


# Slicing ile elemanlara erişmek (array alt kümesine erişmek)

In [164]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [165]:
print(a[0:3])

[20 21 22]


In [166]:
print(a[1::5])

[21 26]


In [167]:
b=np.random.randint(10,size=[5,5])
print(b)


[[9 3 3 8 8]
 [9 5 7 6 1]
 [7 9 9 2 6]
 [8 9 1 6 7]
 [7 4 2 2 2]]


In [168]:
print(b[:,0])

[9 9 7 8 7]


# Alt küme üzerinde işlem yapmak

In [169]:
alt_b=b[0:3,0:2]
print(alt_b)

[[9 3]
 [9 5]
 [7 9]]


In [170]:
alt_b[0,0]=100
print(alt_b)

[[100   3]
 [  9   5]
 [  7   9]]


 # Fancy index
 * Bir liste içine bu arrayden istediğimiz indislerini koyarak o indislerdeki verileri alabiliriz.

In [171]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [172]:
yetgen=[1,3,5]
print(v[yetgen])

[ 3  9 15]


In [173]:
m= np.arange(9).reshape(3,3)
satir=np.array([0,1])
sutun=np.array([1,2])
print(m[satir,sutun])

[1 5]


# Koşullu Eleman İşlemleri 

In [174]:
v = np.array([1,2,3,4,5])
print(v>3)

[False False False  True  True]


In [175]:
print(v[v>3])

[4 5]


In [176]:
print(v[v<3])

[1 2]


# Matematiksel işlemler

In [177]:
v = np.array([1,2,3,4,5])

print(v*2)

[ 2  4  6  8 10]


In [178]:
print(v+2)

[3 4 5 6 7]


In [179]:
print(v*5/2)

[ 2.5  5.   7.5 10.  12.5]


In [180]:
print(np.subtract(v,3)) # Her birinden 3'er eleman çıkarır 'subtract'


[-2 -1  0  1  2]


In [181]:
print(np.add(v,2)) # Toplama işlemi yapar 'add'

[3 4 5 6 7]


In [182]:
print(np.multiply(v,2)) # Çarpma işlemi yapar 'multipy'

[ 2  4  6  8 10]


In [183]:
np.divide(v,2) # Bölme işlemi yapar 'divide'

array([0.5, 1. , 1.5, 2. , 2.5])

In [184]:
np.power(v,2) # Üs alır 'power'

array([ 1,  4,  9, 16, 25], dtype=int32)

In [185]:
np.mod(v,5) # 5'e göre modunu alır 'mod'

array([1, 2, 3, 4, 0], dtype=int32)

In [186]:
print(np.absolute(v)) # Mutlak değer alır 'absolute'

[1 2 3 4 5]


# İki bilinmeyenli denklem çözümü

In [187]:
# 5 * x0 + x1 = 12
# x0 + 3 * x1 = 10
a = np.array([[5,1],[1,3]])
b= np.array([12,10])
x = np.linalg.solve(a,b)
print(x)

[1.85714286 2.71428571]
